-- ============================================================================
-- AIBOS — Prisma-managed migration entry point
-- ============================================================================
-- This file is what `prisma migrate dev` generates from `schema.prisma`.
-- It is committed and applied via `prisma migrate deploy`.
--
-- IMPORTANT: This file is regenerated by Prisma; do not edit manually.
-- RLS policies and pgvector index are created by `prisma/sql/rls.sql` and
-- `prisma/sql/vector_index.sql` which are applied AFTER this migration by
-- the `prisma:deploy` script in `package.json`.
-- ============================================================================

-- (The Prisma-generated DDL for every model in schema.prisma will be inserted
-- here when you run `npx prisma migrate dev --name init`.)

-- Required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";
